import {defineTheme} from '@astryxdesign/core/theme';
import {neutralTheme} from '@astryxdesign/theme-neutral';

const eegFontStack = 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';

const eegThemeDefinition = defineTheme({
  name: 'eeg',
  extends: neutralTheme,
  typography: {
    scale: {base: 15, ratio: 1.18},
    body: {
      family: 'Inter',
      fallbacks: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    heading: {
      family: 'Inter',
      fallbacks: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      weight: 'semibold',
      weights: {1: 'bold', 2: 'semibold', 3: 'semibold'},
    },
    code: {
      family: 'ui-monospace',
      fallbacks: '"SF Mono", Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    },
  },
  radius: {base: 4, multiplier: 0.85},
  motion: {fast: 120, medium: 260, slow: 680, ratio: 0.75, easing: 'cubic-bezier(.2, 0, .2, 1)'},
  tokens: {
    '--color-accent': ['#2b7a78', '#69d4cb'],
    '--color-accent-muted': ['#def2f1', '#173d41'],
    '--color-text-accent': ['#236664', '#8de3db'],
    '--color-icon-accent': ['#2b7a78', '#69d4cb'],
    '--color-on-accent': ['#ffffff', '#102226'],
    '--color-background-body': ['#f4f7f6', '#0d1f23'],
    '--color-background-surface': ['#feffff', '#12262b'],
    '--color-background-card': ['#ffffff', '#162d32'],
    '--color-background-popover': ['#ffffff', '#162d32'],
    '--color-background-muted': ['#eef5f4', '#19383d'],
    '--color-text-primary': ['#17252a', '#f2fbfa'],
    '--color-text-secondary': ['#667579', '#afc2c5'],
    '--color-text-disabled': ['#9badb0', '#6f8588'],
    '--color-icon-primary': ['#17252a', '#f2fbfa'],
    '--color-icon-secondary': ['#667579', '#afc2c5'],
    '--color-border': ['#d8e3e1', '#26454a'],
    '--color-border-emphasized': ['#9cc9c5', '#4b797b'],
    '--color-success': ['#1f7a67', '#8ee2cb'],
    '--color-success-muted': ['#e2f4f1', '#143d37'],
    '--color-warning': ['#785e1d', '#f5cf6b'],
    '--color-warning-muted': ['#fff7df', '#4a3710'],
    '--color-error': ['#a83131', '#ffaaa5'],
    '--color-error-muted': ['#fff1f1', '#4f1d1d'],
    '--color-track': ['#cfdcda', '#34565b'],
    '--color-shadow': ['rgba(18, 38, 43, .08)', 'rgba(0, 0, 0, .38)'],
    '--font-family-body': eegFontStack,
    '--font-family-heading': eegFontStack,
    '--font-weight-normal': '400',
    '--font-weight-medium': '500',
    '--font-weight-semibold': '600',
    '--font-weight-bold': '700',
    '--radius-inner': '4px',
    '--radius-element': '7px',
    '--radius-container': '8px',
    '--radius-page': '12px',
    '--v2-bg': 'var(--color-background-body)',
    '--v2-surface': 'var(--color-background-surface)',
    '--v2-surface-soft': 'var(--color-background-muted)',
    '--v2-ink': 'var(--color-text-primary)',
    '--v2-muted': 'var(--color-text-secondary)',
    '--v2-line': 'var(--color-border)',
    '--v2-accent': 'var(--color-accent)',
    '--v2-accent-strong': 'var(--color-text-accent)',
    '--v2-accent-soft': 'var(--color-accent-muted)',
    '--v2-sidebar': '#17252a',
    '--v2-sidebar-2': '#132126',
    '--v2-sidebar-muted': 'rgba(255, 255, 255, .68)',
    '--v2-shadow': '0 12px 32px var(--color-shadow)',
    '--v2-font-family': 'var(--font-family-body)',
    '--v2-text-xs': '.75rem',
    '--v2-text-sm': '.85rem',
    '--v2-text-md': '.925rem',
    '--v2-text-lg': '1rem',
    '--v2-text-xl': '1.18rem',
    '--v2-text-2xl': '1.32rem',
    '--v2-leading-tight': '1.25',
    '--v2-leading-ui': '1.38',
    '--v2-leading-body': '1.55',
    '--v2-weight-regular': 'var(--font-weight-normal)',
    '--v2-weight-medium': 'var(--font-weight-medium)',
    '--v2-weight-semibold': 'var(--font-weight-semibold)',
    '--v2-weight-bold': 'var(--font-weight-bold)',
    '--v2-button-font-sm': '.9rem',
    '--v2-button-font-md': '.95rem',
    '--v2-button-weight': 'var(--font-weight-semibold)',
    '--v2-button-line': '1',
    '--v2-button-height-sm': '2.5rem',
    '--v2-button-height-md': '2.75rem',
    '--v2-tag-height': '1.75rem',
    '--v2-tag-padding-x': '.58rem',
    '--v2-tag-gap': '.3rem',
    '--v2-tag-radius': 'var(--radius-element)',
    '--v2-tag-font-size': '.85rem',
    '--v2-tag-font-weight': 'var(--font-weight-semibold)',
    '--v2-tag-line-height': '1',
    '--v2-tag-icon-size': '.875rem',
  },
  components: {
    button: {
      base: {
        fontWeight: 'var(--font-weight-semibold)',
        borderRadius: 'var(--radius-element)',
      },
    },
    card: {
      base: {
        borderRadius: 'var(--radius-container)',
      },
    },
    field: {
      base: {
        borderRadius: 'var(--radius-element)',
      },
    },
    banner: {
      base: {
        borderRadius: 'var(--radius-container)',
      },
    },
    table: {
      base: {
        fontFamily: 'var(--font-family-body)',
      },
    },
  },
});

export const eegTheme = {
  ...eegThemeDefinition,
  __built: true,
};
